### ISSUE TITLE
Multiple errors while attempting to utilize shellmath.sh

### ISSUE THREAD

**Issue by toazd** [clarity20/shellfloat#15]
Sorry I cannot be more descriptive with the exact issue. I am short on time and just wanted to quickly try the script.

I cloned the repo and subsequently wrote the following script (the test script is located at a different path: `/home/toazd/github/personal/scripts/bash/misc/sandbox`):
```
#!/usr/bin/env bash

source /home/toazd/github/external/shellmath/shellmath.sh

_shellmath_add 1.2 2.4340 3.1234 4.234314 5.324234
_shellmath_subtract 2.4340 3.1234
_shellmath_multiply 2.4340 3.1234 4.234314 5.324234
_shellmath_divide 2.4340 3.1234
```
And the output after running the previous script:
```
$ ./shellmath1.sh
0.6894
/home/toazd/github/external/shellmath/shellmath.sh: line 484: ((: 063173158332: value too great for base (error token is "063173158332")
/home/toazd/github/external/shellmath/shellmath.sh: line 494: ((: 063173158332: value too great for base (error token is "063173158332")
/home/toazd/github/external/shellmath/shellmath.sh: line 498: ((: 063173158332: value too great for base (error token is "063173158332")
Invalid argument; decimal number required: '154.-4096516847975576672'/home/toazd/github/external/shellmath/shellmath.sh: line 742: ((: 3.1234: syntax error: invalid arithmetic operator (error token is ".1234")
0.7792789908433
```
For reference the answers should be (unless the order is swapped for subtract and divide - I could not find that detail in the readme):
16.315948
-0.6894 (or 0.6894)
171.391142871326
0.779278990843312 (or 1.28323746918652)

**Comment by clarity20** [comment]
A quick status update:
I've reproduced these results and checked in a few fixes. More to come.
- The only error message still standing is the last one, "Invalid argument..."
- My addition result prints out and matches the expected value.
- The subtraction result is positive but should be negative.
- The multiplication is a matter of refining my treatment of finite precision. When I chop off a few digits from the "products of the pairs", I get the desired result.
- The division gives the correct result, but with two fewer decimal digits of precision.

**Comment by toazd** [comment]
Thanks for the update. My results (after a `git pull`) appear to agree with your observations.

```
$ ./shellmath1.sh
16.315948
0.6894
Invalid argument; decimal number required: '154.-4096516847975576672'
0.7792789908433
```

**Comment by clarity20** [comment]
I've fixed that subtraction issue; I'm now getting the correct value of `-0.6894`.
As for multiplication, I'm implementing a technique to get good approximations when the exact calculation exceeds `shellmath`'s precision limits. Will post again when I've rolled this out. 
Thanks for the test cases.

**Comment by clarity20** [comment]
Just checked in a precision/overflow enhancement and I'm getting the correct result for that four-fold multiplication.
For what it's worth, the exact result has even more decimal places than you provided: `171.3911428713264352656`
Next step is to make the division routine more precise.

**Comment by clarity20** [comment]
I've improved the precision of the division routine and I now get `0.779278990843311776` for the above quotient.
With all these calculations now turning out as desired, I'm closing the issue.

**Comment by toazd** [comment]
Just to confirm I ran the original test script again and obtained the following results which all appear correct:
```
$ ./shellmath1.sh 
16.315948
-0.6894
171.3911428713264352656
0.779278990843311776
```
Thanks for both fixing the issue and closing the issue. I have been unexpectedly busy lately. Now, I just need some "me" time so I can tinker with shellmath.
