### ISSUE TITLE
10# can't accept negative fractionalSum

### ISSUE THREAD

**Issue by asmarcz** [clarity20/shellfloat#17]
Hello,
in the comments, you point out "(the "10#" operator) cannot work directly with negative numbers".

Yet $fractionalSum can become negative (line 511) and is later used (line 518 and others) with the 10# operator:
https://github.com/clarity20/shellmath/blob/1734b02339e082c2aaca6aac7a0e9b84b72dcd1f/shellmath.sh#L506-L554

**Comment by asmarcz** [comment]
This can be triggered by:
```
_shellmath_add 0.42 -1.5
```
```
shellmath.sh: line 518: ((: 10#-08: value too great for base (error token is "08")
shellmath.sh: line 530: ((: integerSum < 0 && 10#-08: value too great for base (error token is "08")
shellmath.sh: line 533: ((: integerSum > 0 && 10#-08: value too great for base (error token is "08")
shellmath.sh: line 539: ((: integerSum == 0 && 10#-08: value too great for base (error token is "08")
shellmath.sh: line 546: ((: 10#-08: value too great for base (error token is "08")
shellmath.sh: line 550: ((: 10#-08: value too great for base (error token is "08")
```
```
$ bash --version
GNU bash, version 5.0.0(1)-release (x86_64-pc-linux-gnu)
```

**Comment by asmarcz** [comment]
Most likely related to https://github.com/clarity20/shellmath/issues/16
I imagine Bash 5.1 is stricter in evaluating and thus the problem can be triggered with standard examples.

**Comment by clarity20** [comment]
Thanks for investigating this further. I debugged this today and saw the same behavior in bash-5.1.4, whereas bash-4.4.23 ran it without incident. I've introduced a workaround that tracks the sign of $fractionalSum and produces the correct answer to your example case on both versions. The checkin is # 31207d3.
